# Production Configuration for Z-Commerce Platform
# ================================================

# Production Database Configuration
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:zcommerce_prod}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # Disable H2 console in production
  h2:
    console:
      enabled: false

# Application Configuration
app:
  # Disable demo data initializer in production
  data:
    initializer:
      enabled: false

# Production Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000 # 1 hour for production

# Production AWS Configuration
aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}

# Production Logging
logging:
  level:
    com.zcommerce.platform: WARN
    org.springframework: WARN
    org.springframework.security: WARN
    org.springframework.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/z-commerce/application.log
