# Z-Commerce Platform Configuration
# =================================

server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: z-commerce-platform
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Cache Configuration
  cache:
    type: simple
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: z-commerce-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Application Configuration
app:
  # Demo Data Initializer Configuration
  data:
    initializer:
      # Enable/disable demo data initialization
      # Set to false in production environments
      enabled: true
      # Log level for data initialization
      log-level: INFO

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:your_jwt_secret_key_replace_with_env_variable}
    expiration: 86400000 # 24 hours

# AWS Configuration
aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME:z-commerce-invoices}
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.zcommerce.platform: INFO
    com.zcommerce.platform.config.DataInitializer: INFO
    org.springframework.security: WARN
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
