/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.zcommerce.platform.api;

import com.zcommerce.platform.api.model.CheckInvoiceExists200Response;
import com.zcommerce.platform.api.model.InvoiceUrlResponse;
import com.zcommerce.platform.api.model.MessageResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-10-16T03:23:32.468932+05:30[Asia/Kolkata]")
@Validated
@Tag(name = "Invoices", description = "the Invoices API")
public interface InvoicesApi {

    /**
     * GET /api/v1/invoices/order/{orderId}/exists
     *
     * @param orderId  (required)
     * @return Success (status code 200)
     */
    @Operation(
        operationId = "checkInvoiceExists",
        tags = { "Invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CheckInvoiceExists200Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/invoices/order/{orderId}/exists",
        produces = { "application/json" }
    )
    ResponseEntity<CheckInvoiceExists200Response> checkInvoiceExists(
        @Parameter(name = "orderId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("orderId") Long orderId
    );


    /**
     * DELETE /api/v1/invoices/order/{orderId}
     *
     * @param orderId  (required)
     * @return Success (status code 200)
     */
    @Operation(
        operationId = "deleteInvoice",
        tags = { "Invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MessageResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/v1/invoices/order/{orderId}",
        produces = { "application/json" }
    )
    ResponseEntity<MessageResponse> deleteInvoice(
        @Parameter(name = "orderId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("orderId") Long orderId
    );


    /**
     * POST /api/v1/invoices/order/{orderId}
     *
     * @param orderId  (required)
     * @return Success (status code 201)
     */
    @Operation(
        operationId = "generateInvoice",
        tags = { "Invoices" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Success", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceUrlResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/invoices/order/{orderId}",
        produces = { "application/json" }
    )
    ResponseEntity<InvoiceUrlResponse> generateInvoice(
        @Parameter(name = "orderId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("orderId") Long orderId
    );


    /**
     * GET /api/v1/invoices/order/{orderId}
     *
     * @param orderId  (required)
     * @return Success (status code 200)
     */
    @Operation(
        operationId = "getInvoiceUrl",
        tags = { "Invoices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceUrlResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/invoices/order/{orderId}",
        produces = { "application/json" }
    )
    ResponseEntity<InvoiceUrlResponse> getInvoiceUrl(
        @Parameter(name = "orderId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("orderId") Long orderId
    );

}
